name: flutter_mongodb_realm_besaved
description: Unofficial plugin for using services of the serverless platform MongoDB Realm (previously MongoDB Stitch).
version: 1.2.7
publish_to: 'none'
homepage: https://github.com/BeSavedTech/flutter_mongo_realm_besaved

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mongo_stitch_platform_interface_besaved: ^1.2.4

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
 


  universal_html: ^2.0.8     # instead importing in runtime
  bson: ^1.0.3
  extension: ^0.2.0

  streams_channel_besaved:
    git:
      url: git://github.com/BesavedTech/streams_channel_besaved.git
      ref: master

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_mongo_stitch
        pluginClass: FlutterMongoStitchPlugin
      ios:
        pluginClass: FlutterMongoStitchPlugin
 
